/**
 * Fichiers utf-8 français pour le CMS e107 version 0.8 α
 * anciennement sous /e107_handlers/tiny_mce/
 * Licence GNU/GPL
 * Traducteurs: communauté française e107 http://etalkers.tuxfamily.org/
 *
 * $Source: /cvsroot/touchatou/e107_french/e107_plugins/tinymce/plugins/table/langs/fr.js,v $
 * $Revision: 1.2 $
 * $Date: 2008/06/25 00:06:17 $
 * $Author: marj_nl_fr $
 */

tinyMCE.addToLang('table',{
    general_tab : 'Général',
    advanced_tab : 'Avancé',
    general_props : 'Propriétés générales',
    advanced_props : 'Propriétés avancées',
    desc : 'Insérer/Modifier un tableau',
    row_before_desc : 'Insérer une rangée avant',
    row_after_desc : 'Insérer une rangée après',
    delete_row_desc : ' Supprimer la rangée',
    col_before_desc : 'Insérer une colonne avant',
    col_after_desc : 'Insérer une colonne après',
    delete_col_desc : ' Supprimer la colonne',
    rowtype : 'Type de rangée',
    title : 'Gestionnaire de tableau',
    width : 'Largeur',
    height : 'Hauteur',
    cols : 'Colonnes',
    rows : 'Rangées',
    cellspacing : 'Entre les cellules',
    cellpadding : 'Marges intérieures',
    border : 'Bordures',
    align : 'Alignement horizontal',
    align_default : 'Par défaut',
    align_left : 'À gauche',
    align_right : 'À droite',
    align_middle : 'Centré',
    row_title : 'Propriétés des rangées',
    cell_title : 'Propriétés des cellules',
    cell_type : 'Type de cellule',
    row_desc : 'Propriétés des rangées',
    cell_desc : 'Propriétés des cellules',
    valign : 'Alignement vertical',
    align_top : 'Haut',
    align_bottom : 'Bas',
    props_desc : 'Propriétés du tableau',
    bordercolor : 'Couleur des bordures',
    bgcolor : 'Couleur d\'arrière-plan',
    merge_cells_title : 'Fusionner les cellules',
    split_cells_desc : 'Scinder les cellules',
    merge_cells_desc : 'Fusionner les cellules',
    cut_row_desc : 'Supprimer la rangée',
    copy_row_desc : 'Copier la rangée',
    paste_row_before_desc : 'Coller la rangée avant',
    paste_row_after_desc : 'Coller la rangée après',
    id : 'Id',
    style: 'Style en ligne',
    langdir : 'Sens d\'écriture',
    langcode : 'Code de la langue',
    mime : 'Type MIME de la cible',
    ltr : 'de droite à gauche',
    rtl : 'de gauche à droite',
    bgimage : 'Image d\'arrière-plan',
    summary : 'Descriptif',
    td : "Donnée",
    th : "Entête",
    cell_cell : 'Appliquer à la cellule',
    cell_row : 'Appliquer à toute la rangée',
    cell_all : 'Appliquer à tout le tableau',
    row_row : 'Appliquer à la rangée',
    row_odd : 'Appliquer aux rangées paires',
    row_even : 'Appliquer aux rangées impaires',
    row_all : 'Appliquer à toutes les rangées',
    thead : 'Entête',
    tbody : 'Corps',
    tfoot : 'Pied',
    del : 'Effacer le tableau',
    scope : 'Attribut scope',
    row : 'Rangée',
    col : 'Colonne',
    rowgroup : 'Groupe de rangées',
    colgroup : 'Groupe de colonnes',
    col_limit : 'Vous avez dépassé le nombre maximal de colonnes de {$cols}.',
    row_limit : 'Vous avez dépassé le nombre maximal de rangées de {$rows}.',
    cell_limit : 'Vous avez dépassé le nombre maximal de cellules de {$cells}.',
    missing_scope: 'Les attributs scope rendraient votre tableau de données plus accessible à certains groupes d\'utilisateurs.\n\nÊtes-vous sûr de ne pas vouloir spécifier d\'attribut scope aux cellules d\'entête?\n\n'
});