/**
 * Fichiers utf-8 français pour le CMS e107 version 0.8 α
 * anciennement sous /e107_handlers/tiny_mce/
 * Licence GNU/GPL
 * Traducteurs: communauté française e107 http://etalkers.tuxfamily.org/
 *
 * $Source: /cvsroot/touchatou/e107_french/e107_plugins/tinymce/themes/advanced/langs/fr.js,v $
 * $Revision: 1.1 $
 * $Date: 2008/06/16 15:48:40 $
 * $Author: marj_nl_fr $
 */

tinyMCE.addToLang('',{
    theme_style_select : '-- Style --',
    theme_code_desc : 'Afficher le code source',
    theme_code_title : 'Édition du code source',
    theme_code_wordwrap : 'Retour automatique à la ligne',
    theme_sub_desc : 'Indice',
    theme_sup_desc : 'Exposant',
    theme_hr_desc : 'Insérer une ligne horizontale',
    theme_removeformat_desc : 'Supprimer le formatage',
    theme_custom1_desc : 'Votre description personnalisée ici',
    insert_image_border : 'Bordure',
    insert_image_dimensions : 'Dimensions',
    insert_image_vspace : 'Espacement vertical',
    insert_image_hspace : 'Espacement horizontal',
    insert_image_align : 'Alignement',
    insert_image_align_default : '-- Indéfini --',
    insert_image_align_baseline : 'Ligne de base',
    insert_image_align_top : 'Haut',
    insert_image_align_middle : 'Milieu',
    insert_image_align_bottom : 'Bas',
    insert_image_align_texttop : 'Haut du texte',
    insert_image_align_absmiddle : 'Milieu absolu',
    insert_image_align_absbottom : 'Bas absolu',
    insert_image_align_left : 'À gauche',
    insert_image_align_right : 'À droite',
    theme_font_size : '-- Taille --',
    theme_fontdefault : '-- Police --',
    theme_block : '-- Format --',
    theme_paragraph : 'Paragraphe',
    theme_div : 'Div',
    theme_address : 'Adresse',
    theme_pre : 'Texte préformaté',
    theme_h1 : 'Titre de niveau 1',
    theme_h2 : 'Titre de niveau 2',
    theme_h3 : 'Titre de niveau 3',
    theme_h4 : 'Titre de niveau 4',
    theme_h5 : 'Titre de niveau 5',
    theme_h6 : 'Titre de niveau 6',
    theme_blockquote : 'Citation',
    theme_code : 'Code',
    theme_samp : 'Code en ligne',
    theme_dt : 'Terme de définition ',
    theme_dd : 'description de la définition',
    theme_colorpicker_title : 'Choisir une couleur',
    theme_colorpicker_apply : 'Appliquer',
    theme_forecolor_desc : 'Couleur du texte',
    theme_backcolor_desc : 'Couleur d\'arrière-plan',
    theme_charmap_title : 'Sélectionner un caractère spécial',
    theme_charmap_desc : 'Insérer un caractère spécial',
    theme_visualaid_desc : 'Activer/désactiver les lignes guides et les éléments invisibles',
    insert_anchor_title : 'Gestionnaire d\'ancre',
    insert_anchor_name : 'Nom de l\'ancre',
    theme_anchor_desc : 'Insérer/Modifier une ancre',
    theme_insert_link_titlefield : 'Info-bulle',
    theme_clipboard_msg : 'Pour des raisons de sécurité, les fonctions copier, couper et coller ne sont pas disponibles dans Mozilla et Firefox.\n\nVoulez-vous plus d\'information à ce sujet?\n'
    theme_path : 'élément(s) en cours ',
    cut_desc : 'Couper',
    copy_desc : 'Copier',
    paste_desc : 'Coller',
    link_list : 'Lien de la liste',
    image_list : 'Image de la liste',
    browse : 'Naviguer',
    image_props_desc : 'Propriétés de l\'image',
    newdocument_desc : 'Nouveau document',
    class_name : 'Classe CSS',
    newdocument : 'Êtes-vous sûr de vouloir supprimer tout le contenu?',
    about_title : 'à propos de TinyMCE',
    about : 'à propos',
    license : 'Licence',
    plugins : 'plugins',
    plugin : 'plugin',
    author : 'Auteur',
    version : 'Version',
    loaded_plugins : ' plugins installés',
    help : 'Aide',
    not_set : '-- Indéfini --',
    close : 'Fermer',
    toolbar_focus : 'Atteindre la barre d\'outils (Alt+Q), Atteindre l\'éditeur (Alt+Z), Atteindre l\'élément en cours (Alt+X)',
    invalid_data : 'Erreur: des valeurs incorrectes ont été saisies. Elles sont marquées en rouge.'
});
