/**
 * Fichiers utf-8 français pour le CMS e107 version 0.8 α
 * anciennement sous /e107_handlers/tiny_mce/
 * Licence GNU/GPL
 * Traducteurs: communauté française e107 http://etalkers.tuxfamily.org/
 *
 * $Source: /cvsroot/touchatou/e107_french/e107_plugins/tinymce/plugins/media/langs/fr.js,v $
 * $Revision: 1.1 $
 * $Date: 2008/06/16 15:48:37 $
 * $Author: marj_nl_fr $
 */

tinyMCE.addToLang('media',{
    title : 'Insertion / édition d\'un média',
    desc : 'Insertion / édition d\'un média',
    general : 'Général',
    advanced : 'Avancé',
    file : 'Fichier',
    list : 'Liste',
    size : 'Dimensions',
    preview : 'Prévisualisation',
    constrain_proportions : 'Forcer les proportions',
    type : 'Type',
    id : 'Identifiant (id)',
    name : 'Nom',
    class_name : 'Classe',
    vspace : 'Espacement vertical',
    hspace : 'Espacement horizontal',
    play : 'Lecture automatique',
    loop : 'Boucle',
    menu : 'Montrer le menu',
    quality : 'Qualité',
    scale : 'Echelle',
    align : 'Alignement',
    salign : 'Alignement S',
    wmode : 'Mode W',
    bgcolor : 'Fond',
    base : 'Base',
    flashvars : 'Variables Flash',
    liveconnect : 'SWLiveConnect',
    autohref : 'AutoHREF',
    cache : 'Cache',
    hidden : 'Caché',
    controller : 'Contrôleur',
    kioskmode : 'Mode Kiosque',
    playeveryframe : 'Jouer toutes les images',
    targetcache : 'Cache cible',
    correction : 'Pas de correction',
    enablejavascript : 'Autoriser JavaScript',
    starttime : 'Point de départ',
    endtime : 'Point d\'arrêt',
    href : 'Href',
    qtsrcchokespeed : 'Vitesse de déroulement',
    target : 'Cible',
    volume : 'Volume',
    autostart : 'Démarrage automatique',
    enabled : 'Activé',
    fullscreen : 'Plein écran',
    invokeurls : 'Appel d\'URLs',
    mute : 'Silence',
    stretchtofit : 'Compresser pour ajuster',
    windowlessvideo : 'Vidéo sans fenêtre',
    balance : 'Balance',
    baseurl : 'URL principale',
    captioningid : 'id du titre',
    currentmarker : 'Marqueur courant',
    currentposition : 'Position courante',
    defaultframe : 'Frame par défaut',
    playcount : 'Compteur',
    rate : 'Taux',
    uimode : 'Mode UI',
    flash_options : 'Options Flash',
    qt_options : 'Options Quicktime',
    wmp_options : 'Options Windows media player',
    rmp_options : 'Options Real media player',
    shockwave_options : 'Options Shockwave',
    autogotourl : 'Se rendre automatiquement à l\' URL',
    center : 'Centrer',
    imagestatus : 'Statut de l\'image',
    maintainaspect : 'Maintenir l\'aspect',
    nojava : 'Java interdit',
    prefetch : 'Précharger',
    shuffle : 'Aléatoire',
    console : 'Console',
    numloop : 'Nombre de boucles',
    controls : 'Contrôles',
    scriptcallbacks : 'Script callbacks',
    swstretchstyle : 'Style d\'affichage',
    swstretchhalign : 'Alignement horizontal',
    swstretchvalign : 'Alignement vertical',
    sound : 'Son',
    progress : 'Progression',
    qtsrc : 'QT Src',
    qt_stream_warn : 'Les flux RTSP doivent être ajoutés au champ QT Src dans l\'onglet avancé.\nIl est également préférable d\'ajouter au champ Src une version non streamée…'
});
